// Code generated by goctl. DO NOT EDIT.
package types

type Empty struct {
}

type PageReq struct {
	Page     int `form:"page"`
	PageSize int `form:"page_size"`
}

type Pager struct {
	Page      int `json:"page"`
	PageSize  int `json:"page_size"`
	PageCount int `json:"page_count"`
	Total     int `json:"total"`
}
