// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	mon "go-zero-yun/pkg/monkit"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type authModel interface {
	Conn() *mon.Model
	Insert(ctx context.Context, data *AccessToken) error
	FindOne(ctx context.Context, id string) (*AccessToken, error)
	Update(ctx context.Context, data *AccessToken) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultAccessTokenModel struct {
	conn *mon.Model
}

func newDefaultAccessTokenModel(conn *mon.Model) *defaultAccessTokenModel {
	return &defaultAccessTokenModel{conn: conn}
}

func (m *defaultAccessTokenModel) Conn() *mon.Model {
	return m.conn
}

func (m *defaultAccessTokenModel) Insert(ctx context.Context, data *AccessToken) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreatedAt = time.Now()
		data.UpdatedAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultAccessTokenModel) FindOne(ctx context.Context, id string) (*AccessToken, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data AccessToken

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccessTokenModel) Update(ctx context.Context, data *AccessToken) (*mongo.UpdateResult, error) {
	data.UpdatedAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultAccessTokenModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}
